name: Run R Script and Generate Report
on:
  schedule:
   - cron: '0 0 * * *'  # This runs at midnight
  workflow_dispatch:  # Allows manual workflow execution
jobs:
  run-r-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc libcurl4-openssl-dev libssl-dev libxml2-dev
      
      - name: Install RODBC dependencies
        run: |
          sudo apt-get install -y unixodbc unixodbc-dev odbc-postgresql
      
      - name: Install kableExtra dependencies
        run: |
          sudo apt-get install -y libfontconfig1-dev libharfbuzz-dev libfribidi-dev
      
      - name: Install TinyTeX
        run: |
          Rscript -e "install.packages('tinytex', repos='https://cloud.r-project.org')"
          Rscript -e "tinytex::install_tinytex()"
          
      - name: Install R packages separately
        run: |
          Rscript -e "install.packages('rmarkdown', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('tidyverse', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('httr', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('dplyr', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('readxl', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('knitr', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('kableExtra', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('tidyr', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('ggplot2', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('plotly', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('readr', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('DT', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('formattable', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('googledrive', repos='https://cloud.r-project.org')"
          Rscript -e "install.packages('rvest', repos='https://cloud.r-project.org')"
          
      - name: Install RODBC
        run: |
          Rscript -e "install.packages('RODBC', repos='https://cloud.r-project.org', type='source')"
          
      - name: Verify packages
        run: |
          Rscript -e "packageVersion('kableExtra')"
          Rscript -e "packageVersion('RODBC')"
      
      - name: Check file structure
        run: |
          ls -la sripts/
      
      - name: Run R script and Render HTML
        run: |
          Rscript -e "rmarkdown::render('sripts/reactiva.Rmd', output_format = 'html_document', output_file = '../index.html')"
      
      - name: List output files
        run: ls -l
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
