name: Run R Script and Generate Report

on:
  schedule:
   - cron: '0 0 * * *'  # Esto se ejecuta a la medianoche
  workflow_dispatch:  # Permite la ejecución manual del workflow

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'
      
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ runner.tool_cache }}/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/reporte01.Rmd') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc libcurl4-openssl-dev libssl-dev libxml2-dev
      
      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('rmarkdown', 'tidyverse', 'httr', 'dplyr', 'readxl', 'knitr', 'kableExtra', 'tidyr', 'ggplot2', 'plotly', 'readr', 'DT', 'RODBC', 'formattable', 'googledrive', 'rvest'), dependencies = TRUE)"

      - name: Run R script and Render HTML
        run: |
          Rscript -e "rmarkdown::render('reactiva.Rmd', output_file = 'index.html')"

      - name: List output files
        run: ls -l

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Asegúrate de que el directorio aquí coincida con donde tu archivo HTML es generado
          publish_branch: gh-pages  # ensure it's targeting the gh-pages branch
